name: Balloons
version: '1.0-SNAPSHOT'
main: de.harrisblog.nms.Nms
api-version: 1.19
commands:
  balloons:
    usage: /balloons
permissions:
  balloons.*:
    children:
      - balloons.admin
      - balloons.effects
      - balloons.give
      - balloons.help
      - balloons.reload
  balloons.admin:
    description: /balloons admin
  balloons.effects:
    description: /balloons effects
  balloons.give:
    description: /balloons give
  balloons.help:
    description: /balloons help
  balloons.reload:
    description: /balloons reload


